### ISSUE TITLE
Running on Windows, shebang causes issues

### ISSUE THREAD

**Issue by TheTFo** [yayoc/swagger-to-flowtype#1]
I'm not entirely sure how to fix this yet, I get an error:

> /c/Users/anthony.foster/AppData/npm/swagger-to-flowtype: line 12: /usr/local/bin/node: No such file or directory

I'm sure this is due to Windows, and changing the shebang to:

> /usr/local/bin node

may help.

**Comment by yayoc** [comment]
I updated the shebang path at version 0.0.5.  
I'm not sure if the change solves this issue though.
Could you confirm on your env after updating the version?

@TheTFo

**Comment by TheTFo** [comment]
Looks good!
