### ISSUE TITLE
Issues with generic definitions

### ISSUE THREAD

**Issue by TheTFo** [yayoc/swagger-to-flowtype#3]
If I have definitions such as 

```
Customer: { ... },
IPage[Customer]: { ... },
User: { ...  },
IPage[User] { ... }

```
This causes  an error.

I attempted to solve this by putting in code to replace [ and ] with < and >, however flow doesn't appear to support exporting multiple generic implementations of a class.

```
export type Customer = {...};
export type IPage<Customer> = {...}
export type User = {...}
export type IPage<User> = {...}
```

I know this is a bit vague, but I didn't have time to scrub together an example.  Hopefully this makes sense.

Another possible option, that's not too crazy, would be to drop the last bracket and replace the first with an underscore:

```
export type Customer = {...};
export type IPage_Customer = {...}
export type User = {...}
export type IPage_User = {...}
```

What are your thoughts?  How does the swagger typescript generator handle this?

**Comment by yayoc** [comment]
[This generator](https://github.com/areijngoudt/swagger-ts-generator/blob/876e52e34ad2708c9a26ac1106c04ec804b06f13/lib/modelGenerator.js#L318-L320
) seems to just replace `[ and ]` with `< and >` and `typescript` also doesn't allow to declare duplicate generics.  At this time, I think replacing `[ and ]` with `< and >` would be enough for this library.

**Comment by TheTFo** [comment]
The issue I ran into this is that flow throws errors on the generated
flowtype.js that we have multiple exports of the interface.  Maybe flow
will support this in the future?

**Comment by TheTFo** [comment]
I checked at what https://github.com/swagger-api/swagger-codegen generates for typescript, they basically just remove the generic nature:

```
export interface IPageCustomer
export interface IPageUser
```

I can make this change, are you accepting PR's?

**Comment by yayoc** [comment]
Yes, please create PR.
@TheTFo

**Comment by TheTFo** [comment]
Pull Request #4 waiting to be reviewed.
