### ISSUE TITLE
Optional object type properties

### ISSUE THREAD

**Issue by desmondhume** [yayoc/swagger-to-flowtype#6]
Is it supported as of now? It seems like there's no check on the `required` field of swagger manifest.

For example:

```json
{
  "definitions": {
    "User": {
      "type": "object",
      "required": [
        "email"
      ],
      "properties": {
        "username": {
          "type": "string",
          "description": "User username"
        },
        "email": {
          "type": "string",
          "description": "User email"
        }
      }
    }
  }
}
```

should output: 

```js
export type User = {
  username?: string,
  email: string
};
```

Do you think a PR might be helpful? 

This tool is super useful for me at the moment 😄

**Comment by TheTFo** [comment]
Per the [doc](https://flow.org/en/docs/types/maybe/), I think this should be:

```
export type User = {
  username: ?string,
  email: string
};
```

If not a big deal, put in a PR, and let's review it, and hopefully it'll get merged.  This tool is going to be integral to my workflow if we can make it awesome!

Word of warning, the tool supports both JSON and YAML flavors, so you'll want to get the equivalent in and tested.

**Comment by yayoc** [comment]
Supporting optional looks useful😀
As far as I know, unfortunately, swagger ( ver2 ) is not supporting null type.
So, I think the format should be:

```json
    "NewPet": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "tag": {
          "type": "string"
        }
      }
    }
```

will be

```js
export type NewPet = {
    name: string,
    tag?: string
}
```

**Comment by desmondhume** [comment]
@yayoc @TheTFo I just opened a PR #7. It contains a code rewrite, that should make it easier to add capabilities to the library. 
Apart from optionals, I added a few other improvements, to make the output more expressive and Flow compliant.

**Comment by yayoc** [comment]
Sorry for late reply.
I have checked PR #7, 
an optional feature as default seems a bit strict and be a big change for current users.
Suppose we run this feature as an option by passing an argument like `--check-required`? 

Apart from optional, your code looks nice.
Thanks for your hard work.
@desmondhume

**Comment by desmondhume** [comment]
Ok @yayoc, I could work on a flag to enable/disable optionals and keep the tool familiar to current users.
Let me know if you want to work on it, otherwise I can complete the PR so that it can be merged.

**Comment by yayoc** [comment]
Please work on it @desmondhume 
I am looking forward to your update.

**Comment by desmondhume** [comment]
Hey @yayoc, I just pushed support for `--check-required`, along with tests.

**Comment by yayoc** [comment]
Thanks for your hard work, I have merged @desmondhume
